[package]
name = "libnetrangemerge"
version = "0.1.0"
authors = ["Palmer Cox <p@lmercox.com>"]
edition = "2018"

[dependencies]
cidr = "0.1.1"

[features]
default = ["std"]
std = []

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "merge_benchmark"
harness = false
